name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      
      - name: Install dependencies
        run: |
          pip install \
          jupyter-book \
          ghp-import
      
      - name: Build the book
        run: |
          jupyter-book build content/
      
      - name: Get PR number
        id: pr-info
        run: |
          echo "number=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Deploy with ghp-import
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          ghp-import \
            --no-jekyll \
            --push \
            --force \
            --message "Deploy preview for ${{ steps.pr-info.outputs.number}}" \
            --branch gh-pages \
            --remote origin \
            --prefix=preview/pr-${{ steps.pr-info.outputs.number}} \
            content/_build/html

      - name: Comment PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Preview deployed to: https://${{ github.repository_owner }}.github.io/learn.scientific-python.org/preview/${{ steps.pr-info.outputs.number }}/'
            })
